"""CellSafe-X light visual system and shared chart styling."""
from __future__ import annotations
BG_PRIMARY="#FCFDFC"; BG_SECONDARY="#F5F7F6"; PANEL_PRIMARY="#FFFFFF"; PANEL_SECONDARY="#F7FAF8"; PANEL_ELEVATED="#FFFFFF"; BORDER_SUBTLE="#DFE7E2"
TEXT_PRIMARY="#173C2A"; TEXT_SECONDARY="#60736A"; TEXT_MUTED="#829088"; NAVY="#173C2A"; SLATE=TEXT_SECONDARY
GREEN="#5FA77D"; BLUE="#5B8FB9"; RED="#C75B67"; ACCENT_LIME=GREEN; ACCENT_GREEN="#285F42"; ACCENT_CYAN="#5FA77D"; WARNING="#D4A33E"; HIGH_RISK="#DF7F4D"; CRITICAL=RED; CONFLICT="#7462C7"
STATE_COLORS={"Healthy":GREEN,"Abnormal Heating":WARNING,"Pre-Runaway":HIGH_RISK,"Thermal Runaway":CRITICAL}
RISK_COLORS=((.15,GREEN,"Healthy"),(.40,WARNING,"Watch"),(.70,HIGH_RISK,"High"),(1.01,CRITICAL,"Critical"))
def risk_color(p):
    try: p=float(p)
    except (TypeError,ValueError): return CONFLICT
    return next(c for limit,c,_ in RISK_COLORS if p<limit)
def risk_label(p):
    try: p=float(p)
    except (TypeError,ValueError): return "Unknown"
    return next(label for limit,_,label in RISK_COLORS if p<limit)
def state_color(state): return STATE_COLORS.get(str(state),CONFLICT)
def hex_to_rgba(h,alpha):
    h=str(h).lstrip("#")
    if len(h)!=6:return f"rgba(154,167,161,{alpha})"
    r,g,b=(int(h[i:i+2],16) for i in (0,2,4));return f"rgba({r},{g},{b},{alpha})"
FONT_STACK='Inter, Aptos, "Segoe UI", system-ui, -apple-system, sans-serif'; PLOTLY_COLORWAY=[GREEN,ACCENT_GREEN,BLUE,WARNING,HIGH_RISK,CONFLICT,CRITICAL]; GRID_COLOR="#E9EEEB"; AXIS_COLOR="#D7E0DB"
def plotly_layout(height=300,**overrides):
    axis=dict(gridcolor=GRID_COLOR,zerolinecolor=AXIS_COLOR,linecolor=AXIS_COLOR,tickfont=dict(color=TEXT_SECONDARY,size=13),title=dict(font=dict(color=TEXT_SECONDARY,size=13)))
    layout=dict(height=height,margin=dict(l=16,r=24,t=42,b=18),paper_bgcolor="rgba(0,0,0,0)",plot_bgcolor="#FFFFFF",font=dict(family=FONT_STACK,size=13,color=TEXT_SECONDARY),title=dict(font=dict(size=16,color=NAVY,weight=650),x=0,xanchor="left"),colorway=PLOTLY_COLORWAY,hoverlabel=dict(bgcolor="#FFFFFF",bordercolor=BORDER_SUBTLE,font=dict(family=FONT_STACK,size=13,color=TEXT_PRIMARY)),xaxis=axis.copy(),yaxis=axis.copy(),legend=dict(orientation="h",yanchor="bottom",y=1.03,x=0,font=dict(size=13,color=TEXT_SECONDARY),bgcolor="rgba(0,0,0,0)"));layout.update(overrides);return layout
CSS=f'''<style>
:root{{--bg:{BG_PRIMARY};--side:{BG_SECONDARY};--card:#fff;--green:{NAVY};--active:{ACCENT_GREEN};--teal:{ACCENT_CYAN};--text:{TEXT_PRIMARY};--secondary:{TEXT_SECONDARY};--muted:{TEXT_MUTED};--border:{BORDER_SUBTLE};--font:{FONT_STACK};}}
html,body,.stApp,[class*="css"]{{font-family:var(--font)!important}} .stApp{{background:var(--bg);color:var(--text)}}
header[data-testid="stHeader"]{{background:transparent;height:0;min-height:0}} header[data-testid="stHeader"]>div:first-child,#MainMenu,footer,[data-testid="stStatusWidget"],[data-testid="stDecoration"]{{display:none!important}} [data-testid="stSidebarCollapsedControl"]{{z-index:1000}}
.block-container{{padding:28px 32px 40px!important;max-width:1800px}} h1,h2,h3,h4,h5{{color:var(--green)!important;letter-spacing:-.025em}} p,li,span,label{{color:var(--secondary)}} p,li{{font-size:15px;line-height:1.55}}
section[data-testid="stSidebar"]{{background:var(--side)!important;border-right:1px solid var(--border);width:246px!important}} section[data-testid="stSidebar"]>div{{padding-top:20px}} section[data-testid="stSidebar"] .block-container{{padding:0 14px!important}}
.csx-brand{{display:flex;align-items:center;gap:12px;padding:0 7px 24px;margin-bottom:14px;border-bottom:1px solid var(--border)}} .csx-brand .mark{{width:36px;height:36px;border-radius:9px;background:#E5F1ED;display:grid;place-items:center;flex:0 0 36px}} .csx-brand .name{{font-size:17px;font-weight:700;color:var(--green);line-height:1.15}} .csx-brand .tag{{font-size:12px;color:var(--muted);margin-top:3px}}
.csx-navlabel{{font-size:11px;font-weight:700;letter-spacing:.12em;color:var(--muted);padding:4px 10px 8px}} section[data-testid="stSidebar"] .stButton>button{{width:100%;justify-content:flex-start;text-align:left;border-radius:9px;padding:0 14px;font-size:15px;font-weight:500;height:48px;border:0;box-shadow:none;gap:12px}} section[data-testid="stSidebar"] .stButton>button span[data-testid="stIconMaterial"]{{font-size:18px}} section[data-testid="stSidebar"] .stButton>button[kind="secondary"]{{background:transparent;color:var(--secondary)}} section[data-testid="stSidebar"] .stButton>button[kind="secondary"]:hover{{background:#EAF1ED;color:var(--green)}} section[data-testid="stSidebar"] .stButton>button[kind="primary"]{{background:#E1EFE9;color:#285F42;font-weight:600}} section[data-testid="stSidebar"] div[data-testid="stVerticalBlock"]{{gap:4px}}
.csx-navfoot{{border-top:1px solid var(--border);margin-top:26px;padding:16px 6px 0}} .csx-status-line{{display:flex;align-items:center;gap:8px;font-size:11px;font-weight:600;padding:3px 0;color:var(--secondary)}} .csx-status-line .dot{{width:7px;height:7px;border-radius:50%;background:#43A777}} .csx-status-line .dot.cyan{{display:none}} .csx-status-line:nth-child(2){{display:none}} .csx-version{{font-size:10px;color:var(--muted);padding-top:7px}}
.csx-pagehead{{margin:0 0 24px;display:flex;align-items:flex-start;justify-content:space-between;gap:16px}} .csx-pagehead .title{{font-size:32px;font-weight:700;line-height:1.15;color:var(--green)}} .csx-pagehead .purpose{{font-size:16px;margin-top:6px;color:var(--secondary);line-height:1.45}} .csx-pagehead .meta{{display:flex;gap:8px;align-items:center;padding-top:4px}} .csx-chip{{display:inline-flex;align-items:center;border-radius:999px;padding:6px 11px;font-size:12px;font-weight:600;background:#F5F7F6;border:1px solid var(--border);white-space:nowrap}} .csx-chip.lime,.csx-chip.proto{{display:none}} .csx-chip.cyan{{background:#E5F1ED;color:#285F42;border-color:#D6E9E2}}
.csx-panel-title{{font-size:17px;font-weight:650;color:var(--green);margin-bottom:14px;line-height:1.3}} .csx-section{{font-size:19px;font-weight:650;color:var(--green);margin:24px 0 14px}}
.csx-metric{{background:#fff;border:1px solid var(--border)!important;border-radius:12px;padding:18px 20px;min-height:126px;height:100%;box-shadow:0 1px 2px rgba(24,61,43,.03);display:flex;flex-direction:column;justify-content:center}} .csx-metric .label{{font-size:14px;font-weight:600;color:var(--secondary)}} .csx-metric .value{{font-size:29px;font-weight:700;color:var(--green);margin-top:7px;line-height:1.16;letter-spacing:-.025em}} .csx-metric .value.sm{{font-size:22px;line-height:1.22}} .csx-metric .note{{font-size:14px;color:var(--muted);margin-top:7px;line-height:1.4}}
.csx-metric-grid{{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:16px;margin-bottom:16px}}
.csx-kv{{display:flex;align-items:center;justify-content:space-between;gap:14px;min-height:42px;padding:8px 0;border-bottom:1px solid #E9EEEB}} .csx-kv:last-child{{border-bottom:0}} .csx-kv .k{{font-size:14px;color:var(--secondary)}} .csx-kv .v{{font-size:14px;color:var(--green);font-weight:650;text-align:right}} .csx-note{{font-size:14px;line-height:1.55}} .csx-muted{{font-size:13.5px;color:var(--muted)}} .csx-eq{{background:#F7FAF8;border:1px solid var(--border);border-radius:9px;padding:14px;font-size:14px;color:var(--green);overflow:auto}}
[data-testid="stVerticalBlockBorderWrapper"]{{border-color:var(--border)!important;border-radius:12px!important;background:#fff!important;box-shadow:0 1px 2px rgba(24,61,43,.03);padding:18px 20px!important}} [data-testid="stPlotlyChart"]{{border-radius:9px;overflow:hidden}} [data-testid="stExpander"]{{border-color:var(--border)!important;border-radius:10px!important;background:#fff}} .stSelectbox div[data-baseweb="select"]>div,.stNumberInput input{{border-color:var(--border)!important;background:#fff!important;min-height:44px}} [data-testid="stWidgetLabel"] p{{font-size:14px!important;font-weight:500!important;color:var(--secondary)!important}} div[data-baseweb="tab-list"] button{{font-size:14px;font-weight:600;min-height:42px}} [data-testid="stCaptionContainer"] p{{font-size:13.5px!important;color:var(--muted)!important}} .csx-limitations li{{font-size:15px;line-height:1.55;color:var(--secondary);margin-bottom:9px}} .csx-limitations ul{{margin:0;padding-left:20px}}
@media(max-width:1050px){{.block-container{{padding-left:24px!important;padding-right:24px!important}} .csx-metric-grid{{grid-template-columns:repeat(2,minmax(0,1fr))}}}} @media(max-width:700px){{.block-container{{padding:18px 14px 30px!important}}.csx-pagehead{{display:block}}.csx-pagehead .title{{font-size:28px}}.csx-pagehead .purpose{{font-size:15px}}.csx-pagehead .meta{{margin-top:12px;flex-wrap:wrap}}section[data-testid="stSidebar"]{{width:246px!important}}.csx-metric{{min-height:112px}} .csx-metric-grid{{grid-template-columns:1fr}}}}
</style>'''
